#!/usr/bin/env bash
# verify-acceptance.sh — nRF5340 SPI+BLE P0 acceptance harness.
#
# Runs a clean sysbuild and verifies all P0 acceptance criteria listed in
# REQUIREMENTS.md §6.1 and §6.2. Safe to run repeatedly; always wipes build/.
#
# Assumes NCS v2.9.0 env is already loaded in the shell (e.g. via
#   eval "$(nrfutil toolchain-manager env --ncs-version v2.9.0 --as-script)"
# or its file-based equivalent).

set -u

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

BOARD="nrf5340dk/nrf5340/cpuapp"
BUILD_DIR="build"
APP_NAME="Nordic_nRF5340_SPI_loopback"
APP_BUILD="${BUILD_DIR}/${APP_NAME}"
NET_BUILD="${BUILD_DIR}/ipc_radio"

PASS=0
FAIL=0
TOTAL=0

red()   { printf '\033[31m%s\033[0m' "$*"; }
grn()   { printf '\033[32m%s\033[0m' "$*"; }
yel()   { printf '\033[33m%s\033[0m' "$*"; }

pass() { TOTAL=$((TOTAL + 1)); PASS=$((PASS + 1)); printf "  [%s] %-8s %s\n" "$(grn PASS)" "$1" "$2"; }
fail() { TOTAL=$((TOTAL + 1)); FAIL=$((FAIL + 1)); printf "  [%s] %-8s %s\n" "$(red FAIL)" "$1" "$2"; }

check() {
	# check <id> <description> <cmd...>
	local id="$1" desc="$2"
	shift 2
	if "$@" >/dev/null 2>&1; then
		pass "$id" "$desc"
	else
		fail "$id" "$desc"
	fi
}

banner() {
	echo "========================================================"
	echo " $*"
	echo "========================================================"
}

# ---- Precondition: west on PATH ----
banner "Precondition"
if ! command -v west >/dev/null 2>&1; then
	fail "ENV" "west on PATH (did you source the NCS env?)"
	printf "\n  Hint: source /tmp/ncs_env.sh  (generated by 'nrfutil toolchain-manager env --ncs-version v2.9.0 --as-script')\n\n"
	exit 2
fi
pass "ENV" "west available: $(west --version 2>&1 | head -1)"

# ---- Build ----
banner "Clean sysbuild"
rm -rf "${BUILD_DIR}"
set +e
west build -b "${BOARD}" --sysbuild >/tmp/verify_build.log 2>&1
BUILD_RC=$?
set -e
if [ "${BUILD_RC}" -eq 0 ]; then
	pass "AC-1"  "west build -b ${BOARD} --sysbuild returned 0 (AC-B7 clean rebuild)"
else
	fail "AC-1"  "west build failed (rc=${BUILD_RC}); see /tmp/verify_build.log"
	tail -30 /tmp/verify_build.log
	printf "\nAborting remaining checks.\n"
	exit 1
fi

# ---- Artifacts ----
banner "Build artifacts"
check "AC-2"     "merged.hex exists"                    test -f "${BUILD_DIR}/merged.hex"
check "AC-B4.a"  "app image ELF exists"                 test -f "${APP_BUILD}/zephyr/zephyr.elf"
check "AC-B4.b"  "net core (ipc_radio) ELF exists"      test -f "${NET_BUILD}/zephyr/zephyr.elf"
check "AC-B4.c"  "net core hex exists"                  test -f "${NET_BUILD}/zephyr/zephyr.hex"

# merged.hex must cover BOTH the app core (0x00000000) and the net core
# (0x01000000) address spaces. In Intel HEX this shows up as extended
# linear-address records `:020000040000` and `:020000040001` respectively.
if [ -f "${BUILD_DIR}/merged.hex" ]; then
	if grep -q '^:020000040000' "${BUILD_DIR}/merged.hex" && \
	   grep -q '^:020000040001' "${BUILD_DIR}/merged.hex"; then
		pass "AC-B4.d" "merged.hex covers both app (0x0) and net (0x01000000) regions"
	else
		fail "AC-B4.d" "merged.hex missing one of the core address ranges"
	fi
fi

# ---- DTS ----
banner "Devicetree (app.overlay effect)"
DTS="${APP_BUILD}/zephyr/zephyr.dts"
if [ -f "${DTS}" ]; then
	# Extract the spi@a000 block (SPIM4) into a temp file for simple greps.
	SPIBLK=$(mktemp)
	awk '/spi@a000/{f=1} f{print; if(/^\t};/){exit}}' "${DTS}" > "${SPIBLK}"
	check "AC-B2.a" "SPIM4 status = okay"                    grep -q 'status = "okay"'            "${SPIBLK}"
	check "AC-B2.b" "SPIM4 clock-frequency = 32 MHz"         grep -q 'clock-frequency = < 0x1e84800 >' "${SPIBLK}"
	check "AC-B2.c" "SPIM4 uses pinctrl spi4_default"        grep -q 'pinctrl-0 = < &spi4_default >' "${SPIBLK}"
	rm -f "${SPIBLK}"
else
	fail "AC-B2"    "zephyr.dts not found at ${DTS}"
fi

# ---- Kconfig ----
banner "Kconfig (prj.conf effect)"
CFG="${APP_BUILD}/zephyr/.config"
if [ -f "${CFG}" ]; then
	for sym in \
		CONFIG_SPI \
		CONFIG_SPI_NRFX \
		CONFIG_BT \
		CONFIG_BT_PERIPHERAL \
		CONFIG_BT_HRS \
		CONFIG_BT_DIS \
		CONFIG_BT_HCI_IPC ; do
		check "AC-B3:${sym}" "${sym}=y" grep -q "^${sym}=y" "${CFG}"
	done
	check "AC-B3:NAME"   "CONFIG_BT_DEVICE_NAME=\"nRF5340_HR\"" \
		grep -q '^CONFIG_BT_DEVICE_NAME="nRF5340_HR"' "${CFG}"
else
	fail "AC-B3"    ".config not found at ${CFG}"
fi

# ---- Zephyr modules (sanity for sysbuild hookup) ----
banner "Sysbuild modules"
MODS="${APP_BUILD}/zephyr_modules.txt"
if [ -f "${MODS}" ]; then
	check "AC-B4.e" "nrf module registered for app image" grep -q '"nrf"' "${MODS}"
else
	fail "AC-B4.e" "app zephyr_modules.txt missing at ${MODS}"
fi

# ---- Repo hygiene ----
banner "Repository hygiene"
check "AC-5.a"   ".gitignore excludes build/"          grep -qE '^build/$'  .gitignore
check "AC-5.b"   ".gitignore excludes .west/"          grep -qE '^\.west/$' .gitignore
check "AC-5.c"   ".gitignore excludes .venv/"          grep -qE '^\.venv/$' .gitignore
check "AC-4"     "README contains LLM usage statement" grep -qiE 'llm usage|llm / tool|copilot|claude' README.md

# ---- P2 AC-R2: bsim board compile (optional) ----
# Runs only when BSIM_OUT_PATH+BSIM_COMPONENTS_PATH are already set and
# point to a built BabbleSim install. Compile-only; does not run the sim.
banner "P2: nrf5340bsim compile (optional)"
if [ -n "${BSIM_OUT_PATH:-}" ] && [ -n "${BSIM_COMPONENTS_PATH:-}" ] && \
   [ -d "${BSIM_OUT_PATH}" ] && [ -d "${BSIM_COMPONENTS_PATH}" ]; then
	BSIM_BUILD_DIR="build-bsim"
	rm -rf "${BSIM_BUILD_DIR}"
	set +e
	west build -b nrf5340bsim/nrf5340/cpuapp --build-dir "${BSIM_BUILD_DIR}" \
		>/tmp/verify_bsim.log 2>&1
	BSIM_RC=$?
	set -e
	if [ "${BSIM_RC}" -eq 0 ] && [ -x "${BSIM_BUILD_DIR}/${APP_NAME}/zephyr/zephyr.exe" ]; then
		pass "AC-R2" "nrf5340bsim/nrf5340/cpuapp compiles (zephyr.exe produced)"
	else
		fail "AC-R2" "nrf5340bsim compile failed (rc=${BSIM_RC}); see /tmp/verify_bsim.log"
	fi
else
	printf "  [%s] %-8s %s\n" "$(yel SKIP)" "AC-R2" \
		"bsim vars not set (export BSIM_OUT_PATH + BSIM_COMPONENTS_PATH to enable)"
fi

# ---- Summary ----
banner "Summary"
printf "  Total:  %d\n" "${TOTAL}"
printf "  Passed: %s\n" "$(grn "${PASS}")"
if [ "${FAIL}" -gt 0 ]; then
	printf "  Failed: %s\n" "$(red "${FAIL}")"
	printf "\n%s\n" "$(red '❌ P0 acceptance NOT met.')"
	exit 1
fi
printf "\n%s\n" "$(grn '✅ All P0 acceptance criteria passed.')"
exit 0
